version: "3"

services:
  app:
    build: ./
    restart: always
    ports:
      - "80:80"
    environment:
      - SERVER_PORT=80
      - POSTGRES_DB=db
      - POSTGRES_PASSWORD=secure_db_password
      - FLASK_HOST=flask_backend
      - FLASK_PORT=5000
      - SESSION_SECRET=rxga5vTImReILQB
      - DATABASE_URL=mongodb+srv://gazi:cs326@cluster0.jydbllq.mongodb.net/?retryWrites=true&w=majority
    depends_on:
      - db

  flask_backend:
     build: ./server/flask/

  db:
    image: postgres:15-bullseye
    # restart: always
    environment:
      - POSTGRES_PASSWORD=secure_db_password
    volumes:
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
